basdat_b3/atlet/urls.py
from django.conf.urls import include
from atlet.views import *
from django.urls import path
from atlet.views import *

app_name = 'atlet'

urlpatterns = [
    path('daftar-event/stadium/', event_stadium, name='event_stadium'),
    path('daftar-event/stadium/event/', daftar_event, name='daftar_event'),
    path('daftar-event/stadium/event/kategori', event_kategori, name='event_kategori' ),
    path('enrolled-event/', enrolled_event, name='enrolled_event'),
    path('tes-kualifikasi-form/', tes_kualifikasi_form, name='tes_kualifikasi_form' ),
    path('tes-kualifikasi/', tes_kualifikasi, name='tes_kualifikasi' ),
    path('dashboard-atlet/', dashboard_atlet, name='dashboard_atlet' ),
]

basdat_b3/authentication/urls.py
from django.urls import path
from .views import *

app_name = "authentication"

urlpatterns = [
    path("login/", login, name="login"),
    path("register/", register, name="register"),
    path("", home, name="home"),
    path("atlet/", home, name="atlet"),
]

basdat_b3/basdat_b3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("authentication.urls")),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('atlet/', include('atlet.urls')),
    path('pertandingan/', include('pertandingan.urls')),
    path('pelatih/', include('pelatih.urls')),
    path('umpire/', include('umpire.urls')),
]

basdat_b3/pelatih/urls.py
from django.conf.urls import include
from django.urls import path
from pelatih.views import *

app_name = 'pelatih'

urlpatterns = [
    path('daftar-atlet/', daftar_atlet, name='daftar_atlet'),
    path('list-atlet/', list_atlet, name='list_atlet'),
    path('dashboard-pelatih/', dashboard_pelatih, name='dashboard_pelatih' ),
]

basdat_b3/pertandingan/urls.py
from django.urls import path
from .views import show_pertandingan, show_hasil_pertandingan

app_name = "pertandingan"

urlpatterns = [
    path('', show_pertandingan, name="show_pertandingan"),
    path('hasil/', show_hasil_pertandingan, name="show_hasil_pertandingan"),
]

basdat_b3/sponsor/urls.py
from django.urls import path
from .views import *

app_name = "sponsor"

urlpatterns = [
    path("daftar/", sponsor, name="sponsor"),
]

basdat_b3/umpire/urls.py
from django.urls import path
from umpire.views import dashboard_umpire

app_name = 'umpire'

urlpatterns = [
    path('dashboard-umpire/', dashboard_umpire, name='dashboard_umpire' ),
]

basdat_b3/pertandingan/models.py
from django.db import models

# Create your models here.

basdat_b3/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class LoginForm(UserCreationForm):
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'login-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'login-email', 'placeholder': 'Email'}))


class RegisterAtletForm(UserCreationForm):
    PLAY_CHOICES = [
        ('1', 'Left'),
        ('2', 'Right'),
    ]
    KELAMIN_CHOICES = [
        ('1', 'Laki-laki'),
        ('2', 'Perempuan'),
    ]
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-atlet-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-atlet-email', 'placeholder': 'Email'}))
    negara = forms.CharField(
        label='negara',
        min_length=5,
        max_length=25,
        widget=forms.TextInput(
            attrs={'id': 'register-atlet-negara', 'placeholder': 'Negara'})
    )
    play = forms.CharField(
        label='play',
        widget=forms.RadioSelect(
            choices=PLAY_CHOICES
        )
    )
    tinggi_badan = forms.IntegerField(
        min_value=1,
        max_value=200,
        widget=forms.NumberInput(
            attrs={'id': 'register-atlet-tinggi-badan', 'placeholder': 'Tinggi badam'})
    )
    jenis_kelamin = forms.CharField(
        label='jenis kelamin',
        widget=forms.RadioSelect(
            choices=KELAMIN_CHOICES
        )
    )


class RegisterPelatihForm(UserCreationForm):
    KATEGORI_CHOICES = [
        ('tunggal putra', 'tunggal putra'),
        ('tunggal putri', 'tunggal putri'),
        ('ganda putra', 'ganda putra'),
        ('ganda putri', 'ganda putri'),
        ('ganda campuran', 'ganda campuran'),
    ]
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-pelatih-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-pelatih-email', 'placeholder': 'Email'}))
    negara = forms.CharField(
        label='negara',
        min_length=5,
        max_length=25,
        widget=forms.TextInput(
            attrs={'id': 'register-pelatih-negara', 'placeholder': 'Negara'})
    )
    kategori = forms.MultipleChoiceField(
        label='register-pelatih-kategori',
        widget=forms.CheckboxSelectMultiple,
        choices=KATEGORI_CHOICES)
    tanggal_mulai = forms.DateField(
        label='register-pelatih-tanggal-mulai',
        widget=forms.DateInput(attrs={'type': 'datetime-local'})
    )


class RegisterUmpireForm(UserCreationForm):
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-umpire-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-umpire-email', 'placeholder': 'Email'}))
    negara = forms.CharField(
        label='negara',
        min_length=5,
        max_length=25,
        widget=forms.TextInput(
            attrs={'id': 'register-umpire-negara', 'placeholder': 'Negara'})
    )

basdat_b3/atlet/views.py
from django.shortcuts import render

# Create your views here.


def daftar_event(request):
    return render(request, "daftar_event.html")

def event_stadium(request):
    return render(request, "event_stadium.html")

def event_kategori(request):
    return render(request, "event_kategori.html")

def enrolled_event(request):
    return render(request, "enrolled_event.html")
    
def tes_kualifikasi(request):
    return render(request, "tes_kualifikasi.html")

def tes_kualifikasi_form(request):
    return render(request, "tes_kualifikasi_form.html")

def dashboard_atlet(request):
    return render(request, "dashboard_atlet.html")

basdat_b3/authentication/views.py
from django.shortcuts import render
from authentication.forms import *

# def login(request):
#     if request.method == 'POST':
#         nama = request.POST.get('nama')
#         email = request.POST.get('email')
#         pass
#     context = {'login_form': LoginForm()}
#     return render(request, 'login.html', context)


# def register(request):
#     context = {
#         'atlet_form': RegisterAtletForm(),
#         'pelatih_form': RegisterPelatihForm(),
#         'umpire_form': RegisterUmpireForm(),
#     }
#     return render(request, 'register.html', context)

def home(request):
    return render(request, "home.html")

def login(request):
    return render(request, "login.html")

def register(request):
    return render(request, "register.html")

basdat_b3/dashboard/views.py
from django.shortcuts import render

# Create your views here.

basdat_b3/pelatih/views.py
from django.shortcuts import render

# Create your views here.


def daftar_atlet(request):
    return render(request, "daftar_atlet.html")

def list_atlet(request):
    return render(request, "list_atlet.html")

def dashboard_pelatih(request):
    return render(request, "dashboard_pelatih.html")

basdat_b3/pertandingan/views.py
from django.shortcuts import render

# Create your views here.
def show_pertandingan(request):
    return render(request, "pertandingan.html")

def show_hasil_pertandingan(request):
    return render(request, "hasilPertandingan.html")

basdat_b3/sponsor/views.py
from django.shortcuts import render

# Create your views here.
def sponsor(request):
    return render(request, "sponsor.html")

basdat_b3/umpire/views.py
from django.shortcuts import render

# Create your views here.

def dashboard_umpire(request):
    return render(request, "dashboard_umpire.html")

basdat_b3/atlet/templates/daftar_event.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Event</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<main>
    <section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
            background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
            height: 300px;
            "></div>
    <!-- Background image -->

    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
            margin-top: -200px;
            background: hsla(0, 0%, 100%, 0.8);
            backdrop-filter: blur(30px);
            ">
        <div class="card-body py-5 px-md-5">

        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
            <h2 class="fw-bold mb-5">Daftar Event</h2>
          
            <table width="700" style="margin-left:auto;margin-right:auto">
              <tr>
                <th scope="col">Nama Event</th>
                <th scope="col">Total Hadiah</th>
                <th scope="col">Tanggal Mulai</th>
                <th scope="col">Kategori</th>
                <th scope="col">Kapasitas</th>
                <th scope="col"></th>
              </tr>
              <tr>
                <td>EventA</td>
                <td>Rp 5.000.000</td>
                <td>12-04-2023</td>
                <td>S200</td>
                <td>3/8</td>
                <td>
                  <a class="flex-sm-fill text-sm-center nav-link current" aria-current="page"
                                        href="#">Pilih</a>
                </td>
              </tr>
              <tr>
                <td>EventB</td>
                <td>Rp 4.000.000</td>
                <td>27-07-2023</td>
                <td>S100</td>
                <td>8/8</td>
                <td>
                  <!-- <a class="flex-sm-fill text-sm-center nav-link current" aria-current="page"
                                        href="#t">Pilih</a> -->
                </td>
              </tr>
              <tr>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
              </tr>
            </table>
            </div>
        </div>
        </div>
    </div>
    </section>
</main>
<!-- Section: Design Block -->
<script>
    // Get the container element
    var btnContainer = document.getElementById("nav-member");

    // Get all buttons with class="btn" inside the container
    var btns = btnContainer.getElementsByClassName("nav-link");

    // Loop through the buttons and add the active class to the current/clicked button
    // first tab is active

    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("current");
            current[0].className = current[0].className.replace("current", "");
            this.className += " current";
        });

    }
</script>

<style>
    form {
        display: none;
    }

    form:target {
        display: block;
    }

    .current {
    background: #c9e2bf !important;
    background-color: #c5e2bf !important;
    color: #345531;
    }
</style>
{% endblock content %}

basdat_b3/atlet/templates/dashboard_atlet.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Atlet Dashboard</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<section class="text-center">
  <!-- Background image -->
  <div class="p-5 bg-image" style="
        background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
        height: 300px;
        "></div>
  <!-- Background image -->

  <div class="card mx-4 mx-md-5 shadow-5-strong" style="
        margin-top: -100px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
    <div class="card-body py-5 px-md-5 justify-content-between">
        <div class="row d-flex justify-content-center">
              <h2 class="fw-bold mb-5">Atlet Dashboard</h2>
        <style>
            table {
              border-collapse: collapse;
              width: 200%;
            }
            
            th, td {
              padding: 8px;
              text-align: center;
              border-bottom: 1px solid #ddd;
            }
            
            tr:hover {background-color: greenyellow;}
            </style>
            </head>
            <body>
            
            <table>
              <tr>
                <th>Nama Lengkap</th>
                <th>Negara</th>
                <th>Email</th>
                <th>Tanggal Lahir</th>
                <th>Play (Right/Left Hand)</th>
                <th>Tinggi Badan</th>
                <th>Jenis Kelamin</th>
                <th>Pelatih</th>
                <th>Status</th>
                <th>World Rank</th>
                <th>Total Poin</th>
              </tr>
              <tr>
                <td>Billie Bathurst</td>
                <td>Cina</td>
                <td>bbathurst1@google.com.au</td>
                <td>1998-07-11</td>
                <td>Left</td>
                <td>170</td>
                <td>Perempuan</td>
                <td>Noble MacTague</td>
                <td>Qualified</td>
                <td>55</td>
                <td>217</td>
            </table>            
           
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Design Block -->

{% endblock content %}

basdat_b3/atlet/templates/enrolled_event.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Enrolled Event</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<main>
    <section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
            background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
            height: 300px;
            "></div>
    <!-- Background image -->

    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
            margin-top: -200px;
            background: hsla(0, 0%, 100%, 0.8);
            backdrop-filter: blur(30px);
            ">
        <div class="card-body py-5 px-md-5">

        <div class="row d-flex justify-content-center">
            <h2 class="fw-bold mb-5">Enrolled Event</h2>
            <table>
              <tr>
                <th>Nama Event</th>
                <th>Stadium</th>
                <th>Hadiah</th>
                <th>Kategori Superseries</th>
                <th>Kategori Spesialisasi</th>
                <th>Tanggal Mulai</th>
                <th>Tanggal Selesai</th>
                <th>Kapasitas</th>
                <th></th>
              </tr>
              <tr>
                <td>Event A</td>
                <td>GBK</td>
                <td>Rp 5.000.000</td>
                <td>S200</td>
                <td>Tunggal Putra</td>
                <td>12-04-2023</td>
                <td>15-04-2023</td>
                <td>50/64</td>
                <td><button class="btn btn-primary"><a href="#">Unenroll</a></button></td>
              </tr>
              <tr>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
              </tr>
          </table>
        </div>
        </div>
    </div>
    </section>
</main>

<style>
    form {
        display: none;
    }

    form:target {
        display: block;
    }

    .current {
    background: #c9e2bf !important;
    background-color: #c5e2bf !important;
    color: #345531;
    }
</style>
{% endblock content %}

basdat_b3/atlet/templates/event_kategori.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pilih Kategori</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<main>
    <section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
            background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
            height: 300px;
            "></div>
    <!-- Background image -->

    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
            margin-top: -200px;
            background: hsla(0, 0%, 100%, 0.8);
            backdrop-filter: blur(30px);
            ">
        <div class="card-body py-5 px-md-5">

        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
            <h2 class="fw-bold mb-5">Pilih Kategori</h2>
            <table width="400">
                <tr>
                    <th>Event</th>
                    <td>Event A</td>
                </tr>
                <tr>
                    <th>Hadiah</th>
                    <td>Rp 5.000.000</td>
                </tr>
                <tr>
                    <th>Tanggal Mulai</th>
                    <td>12-04-2023</td>
                </tr>
                    <tr>
                    <th>Tanggal Selesai</th>
                    <td>15-04-2023</td>
                </tr>
                <tr>
                    <th>Kategori</th>
                    <td>S200</td>
                </tr>
                <tr>
                    <th>Kapasitas</th>
                    <td>50/64</td>
                </tr>
                <tr>
                    <th>Stadium</th>
                    <td>GBK</td>
                </tr>
            </tr>
            <tr>
                <th>Negara</th>
                <td>Indonesia</td>
            </tr>
                </tbody>
                </table>
        
            <br></br>
            
            <table border="1.5" width="700" style="margin-left:auto;margin-right:auto">
                <tr>
                    <th>Kategori</th>
                    <th>Partner</th>
                    <th></th>
                </tr>
                <tr>
                    <td>Tunggal Putra</td>
                    <td>-</td>
                    <td>
                        <a href="{% url 'atlet:enrolled_event' %}">Join</a>
                    </td>
                </tr>
                <tr>
                    <td>Ganda Putra</td>
                    <td><select class="dropdown">
                        <option selected>Pilih Atlet</option>
                        <option value="1">Atlet 1</option>
                        <option value="2">Atlet 2</option>
                        <option value="3">Atlet 3</option>
                        </select>
                    </td>
                    <td>
                        <a href="{% url 'atlet:enrolled_event' %}">Join</a>
                    </td>
                </tr>
                <tr>
                    <td>Ganda Campuran</td>
                    <td><select class="dropdown">
                        <option selected>Pilih Atlet</option>
                        <option value="1">Atlet 1</option>
                        <option value="2">Atlet 2</option>
                        <option value="3">Atlet 3</option>
                        </select>
                    </td>
                    <td>
                        <a href="{% url 'atlet:enrolled_event' %}">Join</a>
                    </td>
                </tr>
                </tbody>
                </table>
        </div>
        </div>
        </div>
    </div>
    </section>
</main>

<style>
    form {
        display: none;
    }

    form:target {
        display: block;
    }

    .current {
    background: #c9e2bf !important;
    background-color: #c5e2bf !important;
    color: #345531;
    }
    th, td {
            text-align: left;
        }
</style>
{% endblock content %}

basdat_b3/atlet/templates/event_stadium.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Event</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<main>
    <section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
            background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
            height: 300px;
            "></div>
    <!-- Background image -->

    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
            margin-top: -200px;
            background: hsla(0, 0%, 100%, 0.8);
            backdrop-filter: blur(30px);
            ">
        <div class="card-body py-5 px-md-5">

        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
            <h2 class="fw-bold mb-5">Daftar Event</h2>
          
            <table width="700" style="margin-left:auto;margin-right:auto">
              <tr>
                <th scope="col">Nama Stadium</th>
                <th scope="col">Negara</th>
                <th scope="col">Kapasitas</th>
                <th scope="col"></th>
              </tr>
              <tr>
                <td>GBK</td>
                <td>Indonesia</td>
                <td>8</td>
                <td>
                  <a class="flex-sm-fill text-sm-center nav-link current" aria-current="page"
                                        href="#">Pilih</a>
                </td>
              </tr>
              <tr>
                <td>Senayan</td>
                <td>Indonesia</td>
                <td>16</td>
                <td>
                  <a class="flex-sm-fill text-sm-center nav-link current" aria-current="page"
                                        href="#">Pilih</a>
                </td>
              </tr>
              <tr>
                <td>...</td>
                <td>...</td>
                <td>...</td>
                <td>...</td>
              </tr>
            </table>
            </div>
        </div>
        </div>
    </div>
    </section>
</main>

<!-- Section: Design Block -->
<script>
    // Get the container element
    var btnContainer = document.getElementById("nav-member");

    // Get all buttons with class="btn" inside the container
    var btns = btnContainer.getElementsByClassName("nav-link");

    // Loop through the buttons and add the active class to the current/clicked button
    // first tab is active

    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("current");
            current[0].className = current[0].className.replace("current", "");
            this.className += " current";
        });

    }
</script>

<style>
    form {
        display: none;
    }

    form:target {
        display: block;
    }

    .current {
    background: #c9e2bf !important;
    background-color: #c5e2bf !important;
    color: #345531;
    }
</style>
{% endblock content %}

basdat_b3/atlet/templates/tes_kualifikasi_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<!-- Section: Design Block -->
<section class="text-center">
  <!-- Background image -->
  <div class="p-5 bg-image" style="
        background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
        height: 300px;
        "></div>
  <!-- Background image -->

  <div class="card mx-4 mx-md-5 shadow-5-strong" style="
        margin-top: -100px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
    <div class="card-body py-5 px-md-5 justify-content-between">

      <div class="row d-flex justify-content-center">
        <div class="col-lg-6">
          <h2 class="fw-bold mb-5">Form Data Kualifikasi</h2>
          <form>
            <div class="form-outline mb-4">
              <label class="form-label" for="form3Example3">Nomor Batch</label>
              <input type="nama" id="form3Example3" class="form-control" />
            </div>

            <div class="form-outline mb-4">
                <label class="form-label" for="form3Example3">Tempat Pelaksanaan</label>
                <select class="form-select" aria-label="Default select example">
                    <option selected> </option>
                    <option value="1">Indonesia</option>
                    <option value="2">Thailand</option>
                    <option value="3">Belanda</option>
                    <option value="3">USA</option>
                </select>
            </div>

            <div class="form-outline mb-5">
                <label class="form-label" for="form3Example3">Tanggal Pelaksanaan</label>
                <select class="form-select" aria-label="Default select example">
                <option selected> </option>
                <option value="1">2018-12-21</option>
                <option value="2">2019-08-01</option>
                <option value="3">2022-01-30</option>
                <option value="4">2022-04-13</option>
                </select>
            
            </div>


            <div class="d-grid mt-5">
              <a href="{% url 'atlet:tes_kualifikasi' %}"><button class="btn btn-primary" type="submit">Next</button></a>
            </div>
        </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Design Block -->

{% endblock content %}

basdat_b3/authentication/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Babadu</title>
{% endblock meta %}

{% block content %}
<section class="">
  <!-- Background image -->
  <div class="p-5 bg-image" style="
        background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
        height: 300px;
        "></div>
  <!-- Background image -->

  <div class="card mx-4 mx-md-5 shadow-5-strong" style="
        margin-top: -100px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
    <div class="card-body py-5 px-md-5 justify-content-between">

      <div class="row d-flex justify-content-center">
        <div class="col-lg-8">
          <div class="h-full d-flex flex-column gap-4 justify-content-center align-items-center text-black text-center">
            <section id="header" class="space-y-2">
              <div class="text-black font-weight-bold space-y-2">
                <div class="display-2 text-primary font-weight-bold">Babadu</div>
                <div class="text-lg text-muted max-w-md">
                  Basdat B3
                </div>
            </section>
            <section id="buttons" class="w-100">
              <div class="max-w-lg mx-auto text-black text-lg font-weight-bold">
                <a href="{% url 'authentication:login' %}">
                  <button class="btn btn-primary w-100 py-2 rounded-lg">
                    Login
                  </button>
                </a>
                <div class="d-grid gap-2 my-2">
                  <div class="text-sm">Atau</div>
                </div>
                <a href="{% url 'authentication:register' %}">
                  <button class="btn btn-primary w-100 py-2 rounded-lg">
                    Register
                  </button>
                </a>
              </div>
            </section>
            <section class="h-4"></section>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

basdat_b3/pelatih/templates/daftar_atlet.html
{% extends 'base.html'%}
{% load static %}

{% block meta %}
<title>List Atlet</title>

{% endblock meta %}

{% block content %}

<main>
    <div class="p-5 bg-image" style="
    background-image: url('https://previews.123rf.com/images/elenabukharina/elenabukharina1704/elenabukharina170400068/75888660-let-s-play-badminton-seamless-background-of-badminton-rackets-and-shuttlecocks-pattern.jpg');
    height: 300px;
    "></div>
    <div class="card mx-8 mx-md-5 shadow-5-strong" style="
        margin-top: -200px;
        background: hsla(0, 0%, 100%, 0.8);
        backdrop-filter: blur(30px);
        ">
    <div class="card-body py-5 px-md-5 justify-content-between">
            <h2 class="fw-bold mb-5 text-center">Daftar Atlet</h2>
            <form>
                <div class="mb-3">
                    <label for="inputNama" class="form-label">Atlet yang akan didaftarkan</label>
                    <select class="form-control border border-primary form-select" aria-label="Default select example" required>
                        <option selected>Pilih Atlet</option>
                        <option value="1">Atlet 1</option>
                        <option value="2">Atlet 2</option>
                        <option value="3">...</option>
                      </select>
                </div>
                <div class="d-grid mt-5">
                    <button class="btn btn-primary" type="submit"><a href="{% url 'pelatih:list_atlet' %}">Submit</a></button>
                </div>
            </form>
        </div>
    </div>
</main>

{% endblock content %}

basdat_b3/templates/navbarAtlet.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center" id="main_nav">
            <ul class="navbar-nav">
                <li class="nav-item active"> <a class="nav-link" href="#"> Dashboard </a> </li>
                <li class="nav-item"><a class="nav-link" href="#"> Tes Kualifikasi </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Daftar Event </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Enrolled Event </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Daftar Sponsor </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Logout </a></li>
            </ul>
        </div> <!-- navbar-collapse.// -->
    </div> <!-- container-fluid.// -->
</nav>